/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuCategory {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface MenuItem {
  'id' : string,
  'categoryId' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'isVegetarian' : boolean,
  'price' : bigint,
  'isSpecial' : boolean,
}
export interface Review {
  'id' : string,
  'content' : string,
  'reviewerName' : string,
  'rating' : number,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuCategory' : ActorMethod<[MenuCategory], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReservation' : ActorMethod<
    [string, string, Time, string, bigint, [] | [string]],
    undefined
  >,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getAllMenuCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuCategory' : ActorMethod<[string], [] | [MenuCategory]>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getSpecialMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];